### PR TITLE
feat: extract sync option to env

### PR DESCRIPTION
**Pull request by thephez**
Allows setting sync height option in a single location

### CODE REVIEW

**Comment by riongull** [comment]
This looks like a good improvement. 

You could also extract the entire client instantiation into a separate tutorial segment and replace it with a single line client import in all subsequent segments.

**Comment by thephez** [comment]
> This looks like a good improvement.
> 
I actually made this change locally 6 months ago or something. I don't recall why I never pushed it here :man_shrugging: 

> You could also extract the entire client instantiation into a separate tutorial segment and replace it with a single line client import in all subsequent segments.
I think the original idea was that any of them could be copy/pasted in isolation and be functional, but I like that this abstraction would streamline the individual segments.

Currently we have 2 iterations of the client options - one that defines wallet options (for write ops) and one that doesn't (for read-only ops.

## [Identity register](https://docs.dash.org/projects/platform/en/latest/docs/tutorials/identities-and-names/register-an-identity.html), Contract registration, etc.
```
const clientOpts = {
  network: 'testnet',
  wallet: {
    mnemonic: 'a Dash wallet mnemonic with testnet funds goes here',
    unsafeOptions: {
      skipSynchronizationBeforeHeight: 875000, // only sync from mid-2023
    },
  },
};
const client = new Dash.Client(clientOpts);
```

## [Identity retrieve](https://docs.dash.org/projects/platform/en/latest/docs/tutorials/identities-and-names/retrieve-an-identity.html), contract/name/document retrieve
```
const client = new Dash.Client({ network: 'testnet' });
```

If we extracted client instantiation, would you see it as just having 2 clients in that client segment and the individual segments then just accessing whichever one was relevant? I would want to make such a change in a separate PR, but thought I'd pick your brain since you mentioned it here. :slightly_smiling_face:

**Comment by riongull** [comment]
I would have one client configuration with most or all of the client option keys documented in the passed-in object - scrap the separate `clientOpts` object:

```js
const client = new Dash.Client({
  network: 'testnet',
  wallet: {
    mnemonic: 'a Dash wallet mnemonic with testnet funds goes here',
    unsafeOptions: {
      skipSynchronizationBeforeHeight: 875000, // only sync from mid-2023
    },
  // all other keys, or most if there are too many
  },
});

You could start each comment with "required for reads", "required for writes" or some convention like that. Might also make sense to document what the defaults are.  

A dev wants to know what is optional, required, and default. If that can be done right in copy-pastable code that's ideal in my opinion.  Easiest to have it all in one code block and then let the dev delete or comment out from there.

What @ajcwedev is doing with his tutorial document is translate your docs into a complete quick start that devs can literally follow step by step in a copy paste way. To me, this tutorial presumes that you're most likely going to want to learn how to do writes, not just reads, so I would structure it that way.

Adding this extended info will be more reason to have the client configuration be a separate segment of the tutorial where you to just import the client instance in each subsequent segment.

**Comment by thephez** [comment]
Thanks, I'll take a look! In the meantime, this is what a couple minutes with ChatGPT resulted in: https://github.com/dashpay/platform-tutorials/commit/bf0d5b64694e7fddee73bf98c5e9816fcfcb037e

**Comment by thephez** [comment]
Going to merge this PR. I opened #35 to keep track of the client extraction idea. Feel free to comment there if you have more input.

**Pull request merged**
